### ISSUE TITLE
Where to put the code?

### ISSUE THREAD

**Issue by mateoserendipia** [thehogfather/brackets-custom-region-code-folding#9]
Hi,

This extension is precisely what I was looking for, but I can't seem to get it to work. I have put both code:

"custom-region-fold.startRegionWord": "start"
"custom-region-fold.endRegionWord": "close"

in the brackets.json file, but this doesn't work. Then again, i'm not sure how or where exactly to put that code in that file - the description doesn't offer a screen shot.

I'm rather a brackets-newby, so I apologise for any ignorance - could anybody help?

Thanks!

**Comment by thehogfather** [comment]
Two things
- make sure the .json file is a valid json file. The code above will break because there is no comma after the first line. And to state the obvious, these have to be surrounded by curly braces. Here is my default one and it works fine:

``` javascript
{
    "fonts.fontSize": "12px",
    "fonts.fontFamily": "'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace",
    "themes.theme": "dark-theme",
    "closeBrackets": true,
    "linting.enabled": true,
    "custom-region-fold.endRegionWord": "end",
    "custom-region-fold.startRegionWord": "start"
}
```
- The preference file is called brackets.json for the user level preference or .brackets.json for project preferences (i.e., if placed in the root of your project). Hence make sure the file is in the right place. Happy to help if you are still encountering issues.

**Comment by thehogfather** [comment]
Closing this as there has been no response from reporter. Please reopen if still an issue.
